version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  backend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - backend_data:/app

volumes:
  postgres_data:
  backend_data: